# obligatory fields

name: gitless-snap
version: git
summary: A simple interface to common git operations
description: |
  Gitless is an easy-to-use interface to Git that is also easy to learn.
  It features a simple commit workflow, independent branches, and
  a friendly command-line interface. Because Gitless is implemented on top of
  Git, you can always fall back on Git


base: core20

grade: stable
confinement: strict

architectures:
  - build-on: amd64

# 'optional' fields

apps:
  gitless-snap:
    command: bin/gl
    plugs: [network, network-bind, removable-media]

hooks:
  configure:
    plugs: [home, network, network-bind, removable-media]
  pre-refresh:
    plugs: [home, network, network-bind, removable-media]

parts:
  gitless-cli:
    plugin: python
    source: https://github.com/goldstar611/gitless.git
    stage-packages:
      - git
      - curl
